name: firebase_setup_console
description: "Firebase setup with flutter using console"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  fluttertoast: ^8.2.12
  provider: ^6.1.5
  country_code_picker: ^3.3.0
  google_fonts: ^6.2.1
  dart_format: ^1.4.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.0
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/images/joy_logo.png"

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/categories/
     - assets/banners/
     - assets/suggested/
     - assets/cakes/
     - assets/kids/
     - assets/toys/
flutter_native_splash:
  color: "#ffffff"
  background_image: assets/images/splash_logo.png
  android: true
  ios: true
  fullscreen: true
